<?php

// DO NOT EDIT! This file is auto generated by 'Shopware\Core\Framework\Feature'}
namespace Symfony\Component\DependencyInjection\Loader\Configurator;

return static function(ContainerConfigurator $configurator) {
    $configurator->parameters()->set(
        'shopware.features',
        array (
  'FEATURE_NEXT_1797' => false,
  'FEATURE_NEXT_10549' => false,
  'FEATURE_NEXT_10559' => false,
  'FEATURE_NEXT_10078' => false,
  'FEATURE_NEXT_11389' => false,
  'FEATURE_NEXT_10536' => false,
  'FEATURE_NEXT_7453' => false,
  'FEATURE_NEXT_8172' => false,
)
    );
};