<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3wXa0xy\srcShopware_Production_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3wXa0xy/srcShopware_Production_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/Container3wXa0xy.legacy');

    return;
}

if (!\class_exists(srcShopware_Production_KernelEnvDebugContainer::class, false)) {
    \class_alias(\Container3wXa0xy\srcShopware_Production_KernelEnvDebugContainer::class, srcShopware_Production_KernelEnvDebugContainer::class, false);
}

return new \Container3wXa0xy\srcShopware_Production_KernelEnvDebugContainer([
    'container.build_hash' => '3wXa0xy',
    'container.build_id' => '4f1b3bb3',
    'container.build_time' => 1611397143,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3wXa0xy');
