<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNeRVgpT\srcShopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNeRVgpT/srcShopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerNeRVgpT.legacy');

    return;
}

if (!\class_exists(srcShopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerNeRVgpT\srcShopware_Production_KernelProdContainer::class, srcShopware_Production_KernelProdContainer::class, false);
}

return new \ContainerNeRVgpT\srcShopware_Production_KernelProdContainer([
    'container.build_hash' => 'NeRVgpT',
    'container.build_id' => '8e9b6a5a',
    'container.build_time' => 1611251194,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNeRVgpT');
